In [1]:
import pandas_datareader.data as web
import pandas as pd

In [6]:
all_data = {ticker : web.get_data_yahoo(ticker)
            for ticker in ['AAPL','IBM','MSFT','GOOG']}
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date
 2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0
 2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0
 2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0
 2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0
 2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0
 2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0
 2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0
 2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0
 2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0
 2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0
 2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0
 2010-01-19   30.741428   29.605715   29.761429   30.719999  182501900.0
 2010-01-20   30.792856   29.928572   30.701429   30.247143  153038200.0
 2010-01-21   30.472857   29.601429   30.297142   29.724285  152038600.0
 2010-01-22   29.642857   28.165714   29.540001   28.250000  220441900.0
 2010-01-25   29.242857   28.598572   28.930000   29.010000  266424900.0
 2010-01-26   30.530001   28.940001   29.421429   29.420000  466777500.0
 2010-01-27   30.082857   28.504286   29.549999   29.697144  430642100.0
 2010-01-28   29.357143   28.385714   29.275715   28.469999  293375600.0
 2010-01-29   28.885714   27.178572   28.725714   27.437143  311488100.0
 2010-02-01   28.000000   27.328571   27.481428   27.818571  187469100.0
 2010-02-02   28.045713   27.625713   27.987143   27.980000  174585600.0
 2010-02-03   28.600000   27.774286   27.881428   28.461428  153832000.0
 2010-02-04   28.338572   27.367144   28.104286   27.435715  189413000.0
 2010-02-05   28.000000   27.264286   27.518572   27.922857  212576700.0
 2010-02-08   28.268572   27.714285   27.955715   27.731428  119567700.0
 2010-02-09   28.214285   27.821428   28.059999   28.027143  158221700.0
 2010-02-10   28.085714   27.751429   27.984285   27.874287   92590400.0
 2010-02-11   28.535715   27.722857   27.840000   28.381428  137586400.0
 2010-02-12   28.805714   27.928572   28.301428   28.625713  163867200.0
 ...                ...         ...         ...         ...          ...
 2019-05-17  190.899994  186.759995  186.929993  189.000000   32879100.0
 2019-05-20  184.350006  180.279999  183.520004  183.089996   38612300.0
 2019-05-21  188.000000  184.699997  185.220001  186.600006   28364800.0
 2019-05-22  185.710007  182.550003  184.660004  182.779999   29748600.0
 2019-05-23  180.539993  177.809998  179.800003  179.660004   36529700.0
 2019-05-24  182.139999  178.619995  180.199997  178.970001   23714700.0
 2019-05-28  180.589996  177.910004  178.919998  178.229996   27948200.0
 2019-05-29  179.350006  176.000000  176.419998  177.380005   28481200.0
 2019-05-30  179.229996  176.669998  177.949997  178.300003   21218400.0
 2019-05-31  177.990005  174.990005  176.229996  175.070007   27043600.0
 2019-06-03  177.919998  170.270004  175.600006  173.300003   40396100.0
 2019-06-04  179.830002  174.520004  175.440002  179.639999   30968000.0
 2019-06-05  184.990005  181.139999  184.279999  182.539993   29773400.0
 2019-06-06  185.470001  182.149994  183.080002  185.220001   22526300.0
 2019-06-07  191.919998  185.770004  186.509995  190.149994   30684400.0
 2019-06-10  195.369995  191.619995  191.809998  192.580002   26220900.0
 2019-06-11  196.000000  193.600006  194.860001  194.809998   26932900.0
 2019-06-12  195.970001  193.389999  193.949997  194.190002   18253200.0
 2019-06-13  196.789993  193.600006  194.699997  194.149994   21674600.0
 2019-06-14  193.589996  190.300003  191.550003  192.740005   18761500.0
 2019-06-17  194.960007  192.169998  192.899994  193.889999   14669100.0
 2019-06-18  200.289993  195.210007  196.050003  198.449997   26551000.0
 2019-06-19  199.880005  197.309998  199.679993  197.869995   21124200.0
 2019-06-20  200.610001  198.029999  200.369995  199.460007   21514000.0
 2019-06-21  200.850006  198.149994  198.800003  198.779999   47800600.0
 2019-06-24  200.160004  198.169998  198.539993  198.580002   18220400.0
 2019-06-25  199.259995  195.289993  198.429993  195.570007   21070300.0
 2019-06-26  200.990005  197.350006  197.770004  199.800003   26067500.0
 2019-06-27  201.570007  199.570007  200.289993  199.740005   20899700.0
 2019-06-28  199.500000  197.050003  198.679993  197.919998   31078300.0

              Adj Close
 Date
 2009-12-31   26.372231
 2010-01-04   26.782711
 2010-01-05   26.829010
 2010-01-06   26.402260
 2010-01-07   26.353460
 2010-01-08   26.528664
 2010-01-11   26.294640
 2010-01-12   25.995537
 2010-01-13   26.362217
 2010-01-14   26.209538
 2010-01-15   25.771528
 2010-01-19   26.911612
 2010-01-20   26.497383
 2010-01-21   26.039341
 2010-01-22   24.747818
 2010-01-25   25.413599
 2010-01-26   25.772774
 2010-01-27   26.015560
 2010-01-28   24.940546
 2010-01-29   24.035734
 2010-02-01   24.369871
 2010-02-02   24.511295
 2010-02-03   24.933033
 2010-02-04   24.034487
 2010-02-05   24.461227
 2010-02-08   24.293537
 2010-02-09   24.552589
 2010-02-10   24.418684
 2010-02-11   24.862957
 2010-02-12   25.076958
 ...                ...
 2019-05-17  189.000000
 2019-05-20  183.089996
 2019-05-21  186.600006
 2019-05-22  182.779999
 2019-05-23  179.660004
 2019-05-24  178.970001
 2019-05-28  178.229996
 2019-05-29  177.380005
 2019-05-30  178.300003
 2019-05-31  175.070007
 2019-06-03  173.300003
 2019-06-04  179.639999
 2019-06-05  182.539993
 2019-06-06  185.220001
 2019-06-07  190.149994
 2019-06-10  192.580002
 2019-06-11  194.809998
 2019-06-12  194.190002
 2019-06-13  194.149994
 2019-06-14  192.740005
 2019-06-17  193.889999
 2019-06-18  198.449997
 2019-06-19  197.869995
 2019-06-20  199.460007
 2019-06-21  198.779999
 2019-06-24  198.580002
 2019-06-25  195.570007
 2019-06-26  199.800003
 2019-06-27  199.740005
 2019-06-28  197.919998

 [2389 rows x 6 columns],
 'IBM':                   High         Low        Open       Close      Volume  \
 Date
 2009-12-31  132.850006  130.750000  132.410004  130.899994   4223400.0
 2010-01-04  132.970001  130.850006  131.179993  132.449997   6155300.0
 2010-01-05  131.850006  130.100006  131.679993  130.850006   6841400.0
 2010-01-06  131.490005  129.809998  130.679993  130.000000   5605300.0
 2010-01-07  130.250000  128.910004  129.869995  129.550003   5840600.0
 2010-01-08  130.919998  129.050003  129.070007  130.850006   4197200.0
 2010-01-11  131.059998  128.669998  131.059998  129.479996   5730400.0
 2010-01-12  131.330002  129.000000  129.029999  130.509995   8081500.0
 2010-01-13  131.119995  129.160004  130.389999  130.229996   6455400.0
 2010-01-14  132.710007  129.910004  130.550003  132.309998   7111800.0
 2010-01-15  132.889999  131.089996  132.029999  131.779999   8494400.0
 2010-01-19  134.250000  131.559998  131.630005  134.139999  13916200.0
 2010-01-20  131.149994  128.949997  130.460007  130.250000  15197500.0
 2010-01-21  130.690002  128.059998  130.470001  129.000000   9608600.0
 2010-01-22  128.889999  125.370003  128.669998  125.500000  10088600.0
 2010-01-25  126.889999  125.709999  126.330002  126.120003   5738500.0
 2010-01-26  127.750000  125.410004  125.919998  125.750000   7135300.0
 2010-01-27  126.959999  125.040001  125.820000  126.330002   8719200.0
 2010-01-28  127.040001  123.050003  127.029999  123.750000   9622200.0
 2010-01-29  125.000000  121.900002  124.320000  122.389999  11571200.0
 2010-02-01  124.949997  122.779999  123.230003  124.669998   7242900.0
 2010-02-02  125.809998  123.949997  124.790001  125.529999   5899900.0
 2010-02-03  126.070000  125.070000  125.160004  125.660004   4177100.0
 2010-02-04  125.440002  122.900002  125.190002  123.000000   9126900.0
 2010-02-05  123.720001  121.830002  123.040001  123.519997   8617000.0
 2010-02-08  123.220001  121.739998  123.150002  121.879997   5718500.0
 2010-02-09  124.199997  122.459999  122.650002  123.209999   6044500.0
 2010-02-10  123.650002  122.209999  122.940002  122.809998   5219100.0
 2010-02-11  124.199997  122.059998  122.580002  123.730003   5089000.0
 2010-02-12  124.050003  121.610001  123.010002  124.000000   8017700.0
 ...                ...         ...         ...         ...         ...
 2019-05-17  135.410004  133.940002  134.679993  134.320007   2619100.0
 2019-05-20  135.429993  132.929993  133.529999  135.119995   3264500.0
 2019-05-21  137.059998  135.789993  136.119995  136.449997   2503500.0
 2019-05-22  136.750000  135.710007  136.000000  136.350006   1849800.0
 2019-05-23  135.130005  130.440002  135.130005  132.389999   5343400.0
 2019-05-24  134.250000  131.589996  133.529999  132.279999   2596100.0
 2019-05-28  132.639999  130.270004  132.130005  130.460007   4908800.0
 2019-05-29  130.279999  128.320007  130.000000  129.690002   3679000.0
 2019-05-30  129.970001  128.929993  129.740005  129.570007   2741900.0
 2019-05-31  128.440002  126.849998  128.440002  126.989998   3539300.0
 2019-06-03  128.559998  127.059998  127.099998  128.270004   4266900.0
 2019-06-04  132.740005  129.089996  129.559998  132.690002   3913500.0
 2019-06-05  133.610001  130.470001  133.380005  131.490005   3161300.0
 2019-06-06  132.649994  130.899994  132.190002  132.220001   2298200.0
 2019-06-07  134.720001  132.210007  132.470001  133.309998   2553400.0
 2019-06-10  135.350006  133.910004  134.380005  134.740005   2911300.0
 2019-06-11  136.460007  135.050003  135.320007  135.949997   3407300.0
 2019-06-12  135.940002  134.410004  135.559998  134.869995   2254700.0
 2019-06-13  136.270004  135.089996  135.130005  135.759995   2955300.0
 2019-06-14  135.880005  134.429993  135.440002  135.149994   2193300.0
 2019-06-17  136.029999  134.699997  135.389999  134.949997   2194100.0
 2019-06-18  137.190002  135.199997  135.199997  136.380005   2914700.0
 2019-06-19  138.360001  136.240005  136.429993  137.080002   2382400.0
 2019-06-20  139.539993  138.199997  138.929993  138.850006   3071000.0
 2019-06-21  139.539993  138.389999  138.440002  139.199997   5288700.0
 2019-06-24  140.149994  139.050003  139.199997  139.350006   2186000.0
 2019-06-25  139.550003  138.130005  139.460007  138.360001   2801200.0
 2019-06-26  139.679993  138.410004  138.869995  138.520004   2284600.0
 2019-06-27  139.300003  137.949997  138.720001  138.520004   2149800.0
 2019-06-28  139.139999  137.839996  138.570007  137.899994   6153900.0

              Adj Close
 Date
 2009-12-31   98.137283
 2010-01-04   99.299347
 2010-01-05   98.099792
 2010-01-06   97.462532
 2010-01-07   97.125160
 2010-01-08   98.099792
 2010-01-11   97.072685
 2010-01-12   97.844872
 2010-01-13   97.634964
 2010-01-14   99.194389
 2010-01-15   98.797028
 2010-01-19  100.566330
 2010-01-20   97.649979
 2010-01-21   96.712860
 2010-01-22   94.088844
 2010-01-25   94.553688
 2010-01-26   94.276276
 2010-01-27   94.711105
 2010-01-28   92.776848
 2010-01-29   91.757233
 2010-02-01   93.466576
 2010-02-02   94.111336
 2010-02-03   94.208817
 2010-02-04   92.214569
 2010-02-05   92.604401
 2010-02-08   91.783577
 2010-02-09   92.785126
 2010-02-10   92.483902
 2010-02-11   93.176750
 2010-02-12   93.380051
 ...                ...
 2019-05-17  134.320007
 2019-05-20  135.119995
 2019-05-21  136.449997
 2019-05-22  136.350006
 2019-05-23  132.389999
 2019-05-24  132.279999
 2019-05-28  130.460007
 2019-05-29  129.690002
 2019-05-30  129.570007
 2019-05-31  126.989998
 2019-06-03  128.270004
 2019-06-04  132.690002
 2019-06-05  131.490005
 2019-06-06  132.220001
 2019-06-07  133.309998
 2019-06-10  134.740005
 2019-06-11  135.949997
 2019-06-12  134.869995
 2019-06-13  135.759995
 2019-06-14  135.149994
 2019-06-17  134.949997
 2019-06-18  136.380005
 2019-06-19  137.080002
 2019-06-20  138.850006
 2019-06-21  139.199997
 2019-06-24  139.350006
 2019-06-25  138.360001
 2019-06-26  138.520004
 2019-06-27  138.520004
 2019-06-28  137.899994

 [2389 rows x 6 columns],
 'MSFT':                   High         Low        Open       Close       Volume  \
 Date
 2009-12-31   30.990000   30.480000   30.980000   30.480000   31929700.0
 2010-01-04   31.100000   30.590000   30.620001   30.950001   38409100.0
 2010-01-05   31.100000   30.639999   30.850000   30.959999   49749600.0
 2010-01-06   31.080000   30.520000   30.879999   30.770000   58182400.0
 2010-01-07   30.700001   30.190001   30.629999   30.450001   50559700.0
 2010-01-08   30.879999   30.240000   30.280001   30.660000   51197400.0
 2010-01-11   30.760000   30.120001   30.709999   30.270000   68754700.0
 2010-01-12   30.400000   29.910000   30.150000   30.070000   65912100.0
 2010-01-13   30.520000   30.010000   30.260000   30.350000   51863500.0
 2010-01-14   31.100000   30.260000   30.309999   30.959999   63228100.0
 2010-01-15   31.240000   30.709999   31.080000   30.860001   79913200.0
 2010-01-19   31.240000   30.680000   30.750000   31.100000   46575700.0
 2010-01-20   30.940001   30.309999   30.809999   30.590000   54849500.0
 2010-01-21   30.719999   30.000000   30.610001   30.010000   73086700.0
 2010-01-22   30.200001   28.840000   30.000000   28.959999  102004600.0
 2010-01-25   29.660000   29.100000   29.240000   29.320000   63373000.0
 2010-01-26   29.850000   29.090000   29.200001   29.500000   66639900.0
 2010-01-27   29.820000   29.020000   29.350000   29.670000   63949500.0
 2010-01-28   29.870001   28.889999   29.840000   29.160000  117513700.0
 2010-01-29   29.920000   27.660000   29.900000   28.180000  193888500.0
 2010-02-01   28.480000   27.920000   28.389999   28.410000   85931100.0
 2010-02-02   28.500000   28.139999   28.370001   28.459999   54413700.0
 2010-02-03   28.790001   28.120001   28.260000   28.629999   61397900.0
 2010-02-04   28.500000   27.809999   28.379999   27.840000   77850000.0
 2010-02-05   28.280001   27.570000   28.000000   28.020000   80960100.0
 2010-02-08   28.080000   27.570000   28.010000   27.719999   52820600.0
 2010-02-09   28.340000   27.750000   27.969999   28.010000   59195800.0
 2010-02-10   28.240000   27.840000   28.030001   27.990000   48591300.0
 2010-02-11   28.400000   27.700001   27.930000   28.120001   65993700.0
 2010-02-12   28.059999   27.580000   27.809999   27.930000   81117200.0
 ...                ...         ...         ...         ...          ...
 2019-05-17  130.460007  127.919998  128.309998  128.070007   25770500.0
 2019-05-20  127.589996  125.760002  126.519997  126.220001   23706900.0
 2019-05-21  127.529999  126.580002  127.430000  126.900002   15293300.0
 2019-05-22  128.240005  126.519997  126.620003  127.669998   15396500.0
 2019-05-23  126.290001  124.739998  126.199997  126.180000   23603800.0
 2019-05-24  127.419998  125.970001  126.910004  126.239998   14123400.0
 2019-05-28  128.000000  126.050003  126.980003  126.160004   23128400.0
 2019-05-29  125.389999  124.040001  125.379997  124.940002   22763100.0
 2019-05-30  125.760002  124.779999  125.260002  125.730003   16829600.0
 2019-05-31  124.620003  123.320000  124.230003  123.680000   26646800.0
 2019-06-03  124.370003  119.010002  123.849998  119.839996   37983600.0
 2019-06-04  123.279999  120.650002  121.279999  123.160004   29382600.0
 2019-06-05  125.870003  124.209999  124.949997  125.830002   24926100.0
 2019-06-06  127.970001  125.599998  126.440002  127.820000   21459000.0
 2019-06-07  132.250000  128.259995  129.190002  131.399994   33885600.0
 2019-06-10  134.080002  132.000000  132.399994  132.600006   26477100.0
 2019-06-11  134.240005  131.279999  133.880005  132.100006   23913700.0
 2019-06-12  131.970001  130.710007  131.399994  131.490005   17092500.0
 2019-06-13  133.000000  131.559998  131.979996  132.320007   17200800.0
 2019-06-14  133.789993  131.639999  132.259995  132.449997   17821700.0
 2019-06-17  133.729996  132.529999  132.630005  132.850006   14496200.0
 2019-06-18  135.240005  133.570007  134.190002  135.160004   25934500.0
 2019-06-19  135.929993  133.809998  135.000000  135.690002   23744400.0
 2019-06-20  137.660004  135.720001  137.449997  136.949997   33042600.0
 2019-06-21  137.729996  136.460007  136.580002  136.970001   36727900.0
 2019-06-24  138.399994  137.000000  137.000000  137.779999   20628800.0
 2019-06-25  137.589996  132.729996  137.250000  133.429993   33327400.0
 2019-06-26  135.740005  133.600006  134.350006  133.929993   23657700.0
 2019-06-27  134.710007  133.509995  134.139999  134.149994   16557500.0
 2019-06-28  134.600006  133.160004  134.570007  133.960007   30025500.0

              Adj Close
 Date
 2009-12-31   24.152580
 2010-01-04   24.525019
 2010-01-05   24.532942
 2010-01-06   24.382378
 2010-01-07   24.128809
 2010-01-08   24.295214
 2010-01-11   23.986179
 2010-01-12   23.827694
 2010-01-13   24.049570
 2010-01-14   24.532942
 2010-01-15   24.453693
 2010-01-19   24.643881
 2010-01-20   24.239746
 2010-01-21   23.780155
 2010-01-22   22.948128
 2010-01-25   23.233395
 2010-01-26   23.376024
 2010-01-27   23.510740
 2010-01-28   23.106604
 2010-01-29   22.330048
 2010-02-01   22.512297
 2010-02-02   22.551926
 2010-02-03   22.686628
 2010-02-04   22.060629
 2010-02-05   22.203266
 2010-02-08   21.965540
 2010-02-09   22.195339
 2010-02-10   22.179491
 2010-02-11   22.282507
 2010-02-12   22.131947
 ...                ...
 2019-05-17  128.070007
 2019-05-20  126.220001
 2019-05-21  126.900002
 2019-05-22  127.669998
 2019-05-23  126.180000
 2019-05-24  126.239998
 2019-05-28  126.160004
 2019-05-29  124.940002
 2019-05-30  125.730003
 2019-05-31  123.680000
 2019-06-03  119.839996
 2019-06-04  123.160004
 2019-06-05  125.830002
 2019-06-06  127.820000
 2019-06-07  131.399994
 2019-06-10  132.600006
 2019-06-11  132.100006
 2019-06-12  131.490005
 2019-06-13  132.320007
 2019-06-14  132.449997
 2019-06-17  132.850006
 2019-06-18  135.160004
 2019-06-19  135.690002
 2019-06-20  136.949997
 2019-06-21  136.970001
 2019-06-24  137.779999
 2019-06-25  133.429993
 2019-06-26  133.929993
 2019-06-27  134.149994
 2019-06-28  133.960007

 [2389 rows x 6 columns],
 'GOOG':                    High          Low         Open        Close      Volume  \
 Date
 2009-12-31   310.679321   307.986847   310.356445   307.986847   2455400.0
 2010-01-04   312.721039   310.103088   311.449310   311.349976   3937800.0
 2010-01-05   311.891449   308.761810   311.563568   309.978882   6048500.0
 2010-01-06   310.907837   301.220856   310.907837   302.164703   8009000.0
 2010-01-07   303.029083   294.410156   302.731018   295.130463  12912000.0
 2010-01-08   299.675903   292.651581   294.087250   299.064880   9509900.0
 2010-01-11   300.276978   295.100647   300.276978   298.612823  14519600.0
 2010-01-12   297.147339   292.100159   296.893982   293.332153   9769600.0
 2010-01-13   292.288940   285.095734   286.382355   291.648102  13077600.0
 2010-01-14   295.180145   289.521942   290.063416   293.019196   8535300.0
 2010-01-15   294.862213   287.152344   294.752930   288.126007  10939600.0
 2010-01-19   293.302338   286.283020   288.722137   291.911407   8689500.0
 2010-01-20   291.096710   285.786224   291.096710   288.329681   6543600.0
 2010-01-21   291.513977   284.276062   289.834900   289.606384  12697400.0
 2010-01-22   283.456390   265.701874   280.426086   273.227905  13689200.0
 2010-01-25   273.163330   266.024780   271.528961   268.255249   8897200.0
 2010-01-26   273.024231   266.412231   267.246826   269.457428   8767600.0
 2010-01-27   272.055542   265.925415   268.886169   269.298462   7980200.0
 2010-01-28   271.732635   263.585632   270.485748   265.418701   6500100.0
 2010-01-29   268.747070   261.106750   267.505127   263.257751   8334700.0
 2010-02-01   266.173798   263.436584   265.572693   264.787811   4530800.0
 2010-02-02   265.751556   262.100281   265.751556   263.843964   8245600.0
 2010-02-03   269.298462   262.408295   262.626862   268.662598   6037000.0

In [7]:
price = pd.DataFrame({ticker : data['Adj Close']
                     for ticker ,data in all_data.items()})
price

                  AAPL         IBM        MSFT         GOOG
Date
2009-12-31   26.372231   98.137283   24.152580   307.986847
2010-01-04   26.782711   99.299347   24.525019   311.349976
2010-01-05   26.829010   98.099792   24.532942   309.978882
2010-01-06   26.402260   97.462532   24.382378   302.164703
2010-01-07   26.353460   97.125160   24.128809   295.130463
2010-01-08   26.528664   98.099792   24.295214   299.064880
2010-01-11   26.294640   97.072685   23.986179   298.612823
2010-01-12   25.995537   97.844872   23.827694   293.332153
2010-01-13   26.362217   97.634964   24.049570   291.648102
2010-01-14   26.209538   99.194389   24.532942   293.019196
2010-01-15   25.771528   98.797028   24.453693   288.126007
2010-01-19   26.911612  100.566330   24.643881   291.911407
2010-01-20   26.497383   97.649979   24.239746   288.329681
2010-01-21   26.039341   96.712860   23.780155   289.606384
2010-01-22   24.747818   94.088844   22.948128   273.227905
2010-01-25   25.413599   94.553688   23.233395   268.255249
2010-01-26   25.772774   94.276276   23.376024   269.457428
2010-01-27   26.015560   94.711105   23.510740   269.298462
2010-01-28   24.940546   92.776848   23.106604   265.418701
2010-01-29   24.035734   91.757233   22.330048   263.257751
2010-02-01   24.369871   93.466576   22.512297   264.787811
2010-02-02   24.511295   94.111336   22.551926   263.843964
2010-02-03   24.933033   94.208817   22.686628   268.662598
2010-02-04   24.034487   92.214569   22.060629   261.687958
2010-02-05   24.461227   92.604401   22.203266   263.928406
2010-02-08   24.293537   91.783577   21.965540   265.011353
2010-02-09   24.552589   92.785126   22.195339   266.486755
2010-02-10   24.418684   92.483902   22.179491   265.498199
2010-02-11   24.862957   93.176750   22.282507   266.466888
2010-02-12   25.076958   93.380051   22.131947   264.837494
...                ...         ...         ...          ...
2019-05-17  189.000000  134.320007  128.070007  1162.300049
2019-05-20  183.089996  135.119995  126.220001  1138.849976
2019-05-21  186.600006  136.449997  126.900002  1149.630005
2019-05-22  182.779999  136.350006  127.669998  1151.420044
2019-05-23  179.660004  132.389999  126.180000  1140.770020
2019-05-24  178.970001  132.279999  126.239998  1133.469971
2019-05-28  178.229996  130.460007  126.160004  1134.150024
2019-05-29  177.380005  129.690002  124.940002  1116.459961
2019-05-30  178.300003  129.570007  125.730003  1117.949951
2019-05-31  175.070007  126.989998  123.680000  1103.630005
2019-06-03  173.300003  128.270004  119.839996  1036.229980
2019-06-04  179.639999  132.690002  123.160004  1053.050049
2019-06-05  182.539993  131.490005  125.830002  1042.219971
2019-06-06  185.220001  132.220001  127.820000  1044.339966
2019-06-07  190.149994  133.309998  131.399994  1066.040039
2019-06-10  192.580002  134.740005  132.600006  1080.380005
2019-06-11  194.809998  135.949997  132.100006  1078.719971
2019-06-12  194.190002  134.869995  131.490005  1077.030029
2019-06-13  194.149994  135.759995  132.320007  1088.770020
2019-06-14  192.740005  135.149994  132.449997  1085.349976
2019-06-17  193.889999  134.949997  132.850006  1092.500000
2019-06-18  198.449997  136.380005  135.160004  1103.599976
2019-06-19  197.869995  137.080002  135.690002  1102.329956
2019-06-20  199.460007  138.850006  136.949997  1111.420044
2019-06-21  198.779999  139.199997  136.970001  1121.880005
2019-06-24  198.580002  139.350006  137.779999  1115.520020
2019-06-25  195.570007  138.360001  133.429993  1086.349976
2019-06-26  199.800003  138.520004  133.929993  1079.800049
2019-06-27  199.740005  138.520004  134.149994  1076.010010
2019-06-28  197.919998  137.899994  133.960007  1080.910034

[2389 rows x 4 columns]

In [9]:
volume= pd.DataFrame({ticker: data['Volume']
                     for ticker, data in all_data.items()})
volume

                   AAPL         IBM         MSFT        GOOG
Date
2009-12-31   88102700.0   4223400.0   31929700.0   2455400.0
2010-01-04  123432400.0   6155300.0   38409100.0   3937800.0
2010-01-05  150476200.0   6841400.0   49749600.0   6048500.0
2010-01-06  138040000.0   5605300.0   58182400.0   8009000.0
2010-01-07  119282800.0   5840600.0   50559700.0  12912000.0
2010-01-08  111902700.0   4197200.0   51197400.0   9509900.0
2010-01-11  115557400.0   5730400.0   68754700.0  14519600.0
2010-01-12  148614900.0   8081500.0   65912100.0   9769600.0
2010-01-13  151473000.0   6455400.0   51863500.0  13077600.0
2010-01-14  108223500.0   7111800.0   63228100.0   8535300.0
2010-01-15  148516900.0   8494400.0   79913200.0  10939600.0
2010-01-19  182501900.0  13916200.0   46575700.0   8689500.0
2010-01-20  153038200.0  15197500.0   54849500.0   6543600.0
2010-01-21  152038600.0   9608600.0   73086700.0  12697400.0
2010-01-22  220441900.0  10088600.0  102004600.0  13689200.0
2010-01-25  266424900.0   5738500.0   63373000.0   8897200.0
2010-01-26  466777500.0   7135300.0   66639900.0   8767600.0
2010-01-27  430642100.0   8719200.0   63949500.0   7980200.0
2010-01-28  293375600.0   9622200.0  117513700.0   6500100.0
2010-01-29  311488100.0  11571200.0  193888500.0   8334700.0
2010-02-01  187469100.0   7242900.0   85931100.0   4530800.0
2010-02-02  174585600.0   5899900.0   54413700.0   8245600.0
2010-02-03  153832000.0   4177100.0   61397900.0   6037000.0
2010-02-04  189413000.0   9126900.0   77850000.0   6799200.0
2010-02-05  212576700.0   8617000.0   80960100.0   6353000.0
2010-02-08  119567700.0   5718500.0   52820600.0   5423500.0
2010-02-09  158221700.0   6044500.0   59195800.0   5675700.0
2010-02-10   92590400.0   5219100.0   48591300.0   5383700.0
2010-02-11  137586400.0   5089000.0   65993700.0   4851300.0
2010-02-12  163867200.0   8017700.0   81117200.0   4589000.0
...                 ...         ...          ...         ...
2019-05-17   32879100.0   2619100.0   25770500.0   1208600.0
2019-05-20   38612300.0   3264500.0   23706900.0   1353300.0
2019-05-21   28364800.0   2503500.0   15293300.0   1159800.0
2019-05-22   29748600.0   1849800.0   15396500.0    914500.0
2019-05-23   36529700.0   5343400.0   23603800.0   1198900.0
2019-05-24   23714700.0   2596100.0   14123400.0   1112000.0
2019-05-28   27948200.0   4908800.0   23128400.0   1365000.0
2019-05-29   28481200.0   3679000.0   22763100.0   1538200.0
2019-05-30   21218400.0   2741900.0   16829600.0    951900.0
2019-05-31   27043600.0   3539300.0   26646800.0   1507800.0
2019-06-03   40396100.0   4266900.0   37983600.0   5130600.0
2019-06-04   30968000.0   3913500.0   29382600.0   2833500.0
2019-06-05   29773400.0   3161300.0   24926100.0   2168400.0
2019-06-06   22526300.0   2298200.0   21459000.0   1703200.0
2019-06-07   30684400.0   2553400.0   33885600.0   1802400.0
2019-06-10   26220900.0   2911300.0   26477100.0   1464200.0
2019-06-11   26932900.0   3407300.0   23913700.0   1436700.0
2019-06-12   18253200.0   2254700.0   17092500.0   1061000.0
2019-06-13   21674600.0   2955300.0   17200800.0   1057700.0
2019-06-14   18761500.0   2193300.0   17821700.0   1111500.0
2019-06-17   14669100.0   2194100.0   14496200.0    941600.0
2019-06-18   26551000.0   2914700.0   25934500.0   1386700.0
2019-06-19   21124200.0   2382400.0   23744400.0   1338800.0
2019-06-20   21514000.0   3071000.0   33042600.0   1262000.0
2019-06-21   47800600.0   5288700.0   36727900.0   1947600.0
2019-06-24   18220400.0   2186000.0   20628800.0   1395600.0
2019-06-25   21070300.0   2801200.0   33327400.0   1546900.0
2019-06-26   26067500.0   2284600.0   23657700.0   1810900.0
2019-06-27   20899700.0   2149800.0   16557500.0   1004300.0
2019-06-28   31078300.0   6153900.0   30025500.0   1693200.0

[2389 rows x 4 columns]

In [11]:
returns = price.pct_change()
returns

                AAPL       IBM      MSFT      GOOG
Date
2009-12-31       NaN       NaN       NaN       NaN
2010-01-04  0.015565  0.011841  0.015420  0.010920
2010-01-05  0.001729 -0.012080  0.000323 -0.004404
2010-01-06 -0.015906 -0.006496 -0.006137 -0.025209
2010-01-07 -0.001848 -0.003462 -0.010400 -0.023279
2010-01-08  0.006648  0.010035  0.006897  0.013331
2010-01-11 -0.008822 -0.010470 -0.012720 -0.001512
2010-01-12 -0.011375  0.007955 -0.006607 -0.017684
2010-01-13  0.014106 -0.002145  0.009312 -0.005741
2010-01-14 -0.005792  0.015972  0.020099  0.004701
2010-01-15 -0.016712 -0.004006 -0.003230 -0.016699
2010-01-19  0.044238  0.017908  0.007777  0.013138
2010-01-20 -0.015392 -0.028999 -0.016399 -0.012270
2010-01-21 -0.017286 -0.009597 -0.018960  0.004428
2010-01-22 -0.049599 -0.027132 -0.034988 -0.056554
2010-01-25  0.026903  0.004940  0.012431 -0.018200
2010-01-26  0.014133 -0.002934  0.006139  0.004481
2010-01-27  0.009420  0.004612  0.005763 -0.000590
2010-01-28 -0.041322 -0.020423 -0.017189 -0.014407
2010-01-29 -0.036279 -0.010990 -0.033608 -0.008142
2010-02-01  0.013902  0.018629  0.008162  0.005812
2010-02-02  0.005803  0.006898  0.001760 -0.003565
2010-02-03  0.017206  0.001036  0.005973  0.018263
2010-02-04 -0.036038 -0.021168 -0.027593 -0.025961
2010-02-05  0.017755  0.004227  0.006466  0.008562
2010-02-08 -0.006855 -0.008864 -0.010707  0.004103
2010-02-09  0.010663  0.010912  0.010462  0.005567
2010-02-10 -0.005454 -0.003246 -0.000714 -0.003710
2010-02-11  0.018194  0.007492  0.004645  0.003649
2010-02-12  0.008607  0.002182 -0.006757 -0.006115
...              ...       ...       ...       ...
2019-05-17 -0.005682 -0.011481 -0.006670 -0.014148
2019-05-20 -0.031270  0.005956 -0.014445 -0.020176
2019-05-21  0.019171  0.009843  0.005387  0.009466
2019-05-22 -0.020472 -0.000733  0.006068  0.001557
2019-05-23 -0.017070 -0.029043 -0.011671 -0.009249
2019-05-24 -0.003841 -0.000831  0.000475 -0.006399
2019-05-28 -0.004135 -0.013759 -0.000634  0.000600
2019-05-29 -0.004769 -0.005902 -0.009670 -0.015598
2019-05-30  0.005187 -0.000925  0.006323  0.001335
2019-05-31 -0.018116 -0.019912 -0.016305 -0.012809
2019-06-03 -0.010110  0.010080 -0.031048 -0.061071
2019-06-04  0.036584  0.034459  0.027704  0.016232
2019-06-05  0.016143 -0.009044  0.021679 -0.010284
2019-06-06  0.014682  0.005552  0.015815  0.002034
2019-06-07  0.026617  0.008244  0.028008  0.020779
2019-06-10  0.012779  0.010727  0.009133  0.013452
2019-06-11  0.011580  0.008980 -0.003771 -0.001537
2019-06-12 -0.003183 -0.007944 -0.004618 -0.001567
2019-06-13 -0.000206  0.006599  0.006312  0.010900
2019-06-14 -0.007262 -0.004493  0.000982 -0.003141
2019-06-17  0.005967 -0.001480  0.003020  0.006588
2019-06-18  0.023518  0.010597  0.017388  0.010160
2019-06-19 -0.002923  0.005133  0.003921 -0.001151
2019-06-20  0.008036  0.012912  0.009286  0.008246
2019-06-21 -0.003409  0.002521  0.000146  0.009411
2019-06-24 -0.001006  0.001078  0.005914 -0.005669
2019-06-25 -0.015158 -0.007104 -0.031572 -0.026149
2019-06-26  0.021629  0.001156  0.003747 -0.006029
2019-06-27 -0.000300  0.000000  0.001643 -0.003510
2019-06-28 -0.009112 -0.004476 -0.001416  0.004554

[2389 rows x 4 columns]

In [12]:
returns.tail()

                AAPL       IBM      MSFT      GOOG
Date
2019-06-24 -0.001006  0.001078  0.005914 -0.005669
2019-06-25 -0.015158 -0.007104 -0.031572 -0.026149
2019-06-26  0.021629  0.001156  0.003747 -0.006029
2019-06-27 -0.000300  0.000000  0.001643 -0.003510
2019-06-28 -0.009112 -0.004476 -0.001416  0.004554

In [13]:
returns['MSFT'].corr(returns['IBM'])

0.4870662736206456

In [14]:
returns.corr()

          AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.379346  0.453043  0.460606
IBM   0.379346  1.000000  0.487066  0.403020
MSFT  0.453043  0.487066  1.000000  0.537925
GOOG  0.460606  0.403020  0.537925  1.000000

In [15]:
returns.cov()

          AAPL       IBM      MSFT      GOOG
AAPL  0.000266  0.000076  0.000107  0.000116
IBM   0.000076  0.000151  0.000087  0.000077
MSFT  0.000107  0.000087  0.000209  0.000120
GOOG  0.000116  0.000077  0.000120  0.000239

In [16]:
returns.AAPL

Date
2009-12-31         NaN
2010-01-04    0.015565
2010-01-05    0.001729
2010-01-06   -0.015906
2010-01-07   -0.001848
2010-01-08    0.006648
2010-01-11   -0.008822
2010-01-12   -0.011375
2010-01-13    0.014106
2010-01-14   -0.005792
2010-01-15   -0.016712
2010-01-19    0.044238
2010-01-20   -0.015392
2010-01-21   -0.017286
2010-01-22   -0.049599
2010-01-25    0.026903
2010-01-26    0.014133
2010-01-27    0.009420
2010-01-28   -0.041322
2010-01-29   -0.036279
2010-02-01    0.013902
2010-02-02    0.005803
2010-02-03    0.017206
2010-02-04   -0.036038
2010-02-05    0.017755
2010-02-08   -0.006855
2010-02-09    0.010663
2010-02-10   -0.005454
2010-02-11    0.018194
2010-02-12    0.008607
                ...
2019-05-17   -0.005682
2019-05-20   -0.031270
2019-05-21    0.019171
2019-05-22   -0.020472
2019-05-23   -0.017070
2019-05-24   -0.003841
2019-05-28   -0.004135
2019-05-29   -0.004769
2019-05-30    0.005187
2019-05-31   -0.018116
2019-06-03   -0.010110
2019-06-04    0.036584
2019-06-05    0.016143
2019-06-06    0.014682
2019-06-07    0.026617
2019-06-10    0.012779
2019-06-11    0.011580
2019-06-12   -0.003183
2019-06-13   -0.000206
2019-06-14   -0.007262
2019-06-17    0.005967
2019-06-18    0.023518
2019-06-19   -0.002923
2019-06-20    0.008036
2019-06-21   -0.003409
2019-06-24   -0.001006
2019-06-25   -0.015158
2019-06-26    0.021629
2019-06-27   -0.000300
2019-06-28   -0.009112
Name: AAPL, Length: 2389, dtype: float64

In [24]:
returns.corrwith(returns.IBM)

AAPL    0.379346
IBM     1.000000
MSFT    0.487066
GOOG    0.403020
dtype: float64

In [31]:
!type examples\ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [26]:
df = pd.read_csv('examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [33]:
pd.read_table('examples/ex1.csv',sep=',')

E:\anaconda\anacondasetup\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [34]:
!type examples\ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [37]:
pd.read_csv('examples\ex2.csv',header =None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [39]:
pd.read_csv('examples\ex2.csv')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [41]:
pd.read_csv('examples/ex2.csv',names=['a','b','c','d','message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [42]:
pd.read_csv('examples/ex2.csv',names=['a','b','c','d','message'],index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [45]:
!type examples\csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [47]:
parsed = pd.read_csv('examples/csv_mindex.csv',index_col=['key1','key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [48]:
list(open('examples/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [50]:
result = pd.read_table('examples\ex3.txt',sep='\s+')
result

E:\anaconda\anacondasetup\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [51]:
!type examples\ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [53]:
pd.read_csv('examples\ex4.csv',skiprows=[0,2,3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [54]:
!type examples\ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [56]:
result = pd.read_csv('examples/ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [57]:
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [67]:
result = pd.read_csv('examples/ex5.csv',na_values=['9'])
result

  something    a   b     c   d message
0       one  1.0   2   3.0   4     NaN
1       two  5.0   6   NaN   8   world
2     three  NaN  10  11.0  12     foo

In [68]:
result.iloc[0,5] == '9'

False

In [71]:
sensinels={'message':['foo','NA'],'something':['two']}
result = pd.read_csv('examples/ex5.csv',na_values=sensinels)
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [72]:
pd.options.display.max_rows=10

In [75]:
result = pd.read_csv('examples/ex6.csv',nrows=4)
result

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R

In [76]:
chunker = pd.read_csv('examples/ex6.csv',chunksize=1000)
chunker

In [78]:
tot=pd.Series()
tot

Series([], dtype: float64)

In [79]:
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(),fill_value=0)
tot=tot.sort_values(ascending=False)

In [80]:
tot

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
     ...
5    157.0
2    152.0
0    151.0
9    150.0
1    146.0
Length: 36, dtype: float64

In [81]:
data = pd.read_csv('examples/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [83]:
data.to_csv('examples/out.csv')

In [85]:
!type examples\out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [86]:
import sys

In [88]:
data.to_csv(sys.stdout,sep='|',na_rep='NULL')

|something|a|b|c|d|message
0|one|1|2|3.0|4|NULL
1|two|5|6|NULL|8|world
2|three|9|10|11.0|12|foo

In [90]:
data.to_csv(sys.stdout,index=False,header=False,na_rep='NULL')

one,1,2,3.0,4,NULL
two,5,6,NULL,8,world
three,9,10,11.0,12,foo

In [92]:
data.to_csv(sys.stdout,index=False,columns=['a','b','c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [94]:
datas = pd.date_range('1/1/2000',periods=7)
datas

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [98]:
import numpy as np
ts = pd.Series(np.arange(7),index=datas)
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int32

In [99]:
ts.to_csv('examples/teseries.csv')

E:\anaconda\anacondasetup\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [100]:
!type examples\teseries.csv

2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6

In [101]:
!type examples\ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [103]:
import csv
with open ('examples/ex7.csv') as f:
    lines = list(csv.reader(f))
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [104]:
header , values = lines[0],lines[1:]

In [105]:
values

[['1', '2', '3'], ['1', '2', '3']]

In [106]:
data_dict = {h: v for h,v in zip(header,zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [107]:
import json

In [111]:
obj="""{
    "name": "Wes",
    "place":["united","spain"],
    "pet": null
}
"""

In [113]:
result =json.loads(obj)
result

{'name': 'Wes', 'place': ['united', 'spain'], 'pet': None}

In [115]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "place": ["united", "spain"], "pet": null}'

In [116]:
! type examples\example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [117]:
data = pd.read_json('examples\example.json')

In [118]:
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [119]:
print(data.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [120]:
print(data.to_json(orient='records'))

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [11]:
import lxml
table = pd.read_html('fdic_failed_bank_list.html')

ValueError: No tables found

In [12]:
frame = pd.read_csv('examples/ex1.csv')

In [13]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [15]:
frame.to_pickle('examples/frame_pickle')

In [16]:
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [20]:
import numpy as np
frame = pd.DataFrame({'a':np.random.randn(100)})
frame

           a
0   0.633309
1  -0.578605
2   1.625173
3  -0.511916
4  -0.248164
5  -0.731175
6  -0.943519
7   1.103776
8  -0.974434
9  -2.352491
10  0.143088
11 -1.830948
12 -0.518065
13  0.361674
14  1.242784
15  1.104918
16  0.033410
17  1.052417
18 -0.273428
19  0.407885
20 -1.330633
21 -0.134865
22  0.594948
23 -2.187803
24 -0.103046
25  2.052557
26 -0.546096
27 -0.491227
28  0.884943
29  1.057984
..       ...
70 -0.465007
71 -0.346390
72  0.718370
73  0.065433
74  1.116200
75 -0.997305
76 -0.531486
77 -2.474904
78 -1.737615
79  0.442952
80  1.135111
81 -0.801447
82  0.018699
83 -0.789884
84  0.886172
85 -0.733135
86 -2.708758
87  1.830878
88  1.457729
89 -0.786749
90  2.901167
91 -1.310085
92  0.990905
93 -1.346976
94 -0.333435
95 -0.831393
96 -0.950219
97 -0.259614
98  1.929833
99 -0.436615

[100 rows x 1 columns]

In [22]:
store = pd.HDFStore('mydata.h5')

In [23]:
store['obj1']=frame

In [24]:
store['obj1_col']=frame['a']

In [25]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [29]:
store['obj1']

           a
0   0.633309
1  -0.578605
2   1.625173
3  -0.511916
4  -0.248164
5  -0.731175
6  -0.943519
7   1.103776
8  -0.974434
9  -2.352491
10  0.143088
11 -1.830948
12 -0.518065
13  0.361674
14  1.242784
15  1.104918
16  0.033410
17  1.052417
18 -0.273428
19  0.407885
20 -1.330633
21 -0.134865
22  0.594948
23 -2.187803
24 -0.103046
25  2.052557
26 -0.546096
27 -0.491227
28  0.884943
29  1.057984
..       ...
70 -0.465007
71 -0.346390
72  0.718370
73  0.065433
74  1.116200
75 -0.997305
76 -0.531486
77 -2.474904
78 -1.737615
79  0.442952
80  1.135111
81 -0.801447
82  0.018699
83 -0.789884
84  0.886172
85 -0.733135
86 -2.708758
87  1.830878
88  1.457729
89 -0.786749
90  2.901167
91 -1.310085
92  0.990905
93 -1.346976
94 -0.333435
95 -0.831393
96 -0.950219
97 -0.259614
98  1.929833
99 -0.436615

[100 rows x 1 columns]

In [33]:
store['obj1_col']

0     0.633309
1    -0.578605
2     1.625173
3    -0.511916
4    -0.248164
5    -0.731175
6    -0.943519
7     1.103776
8    -0.974434
9    -2.352491
10    0.143088
11   -1.830948
12   -0.518065
13    0.361674
14    1.242784
15    1.104918
16    0.033410
17    1.052417
18   -0.273428
19    0.407885
20   -1.330633
21   -0.134865
22    0.594948
23   -2.187803
24   -0.103046
25    2.052557
26   -0.546096
27   -0.491227
28    0.884943
29    1.057984
        ...
70   -0.465007
71   -0.346390
72    0.718370
73    0.065433
74    1.116200
75   -0.997305
76   -0.531486
77   -2.474904
78   -1.737615
79    0.442952
80    1.135111
81   -0.801447
82    0.018699
83   -0.789884
84    0.886172
85   -0.733135
86   -2.708758
87    1.830878
88    1.457729
89   -0.786749
90    2.901167
91   -1.310085
92    0.990905
93   -1.346976
94   -0.333435
95   -0.831393
96   -0.950219
97   -0.259614
98    1.929833
99   -0.436615
Name: a, Length: 100, dtype: float64

In [34]:
store.close()

In [37]:
pd.read_hdf('mydata.h5','obj1')

           a
0   0.633309
1  -0.578605
2   1.625173
3  -0.511916
4  -0.248164
5  -0.731175
6  -0.943519
7   1.103776
8  -0.974434
9  -2.352491
10  0.143088
11 -1.830948
12 -0.518065
13  0.361674
14  1.242784
15  1.104918
16  0.033410
17  1.052417
18 -0.273428
19  0.407885
20 -1.330633
21 -0.134865
22  0.594948
23 -2.187803
24 -0.103046
25  2.052557
26 -0.546096
27 -0.491227
28  0.884943
29  1.057984
..       ...
70 -0.465007
71 -0.346390
72  0.718370
73  0.065433
74  1.116200
75 -0.997305
76 -0.531486
77 -2.474904
78 -1.737615
79  0.442952
80  1.135111
81 -0.801447
82  0.018699
83 -0.789884
84  0.886172
85 -0.733135
86 -2.708758
87  1.830878
88  1.457729
89 -0.786749
90  2.901167
91 -1.310085
92  0.990905
93 -1.346976
94 -0.333435
95 -0.831393
96 -0.950219
97 -0.259614
98  1.929833
99 -0.436615

[100 rows x 1 columns]

In [39]:
xlsx = pd.ExcelFile('examples/ex1.xlsx')
xlsx

In [42]:
frame=pd.read_excel(xlsx,'Sheet1')

In [45]:
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [46]:
frame.to_excel("examples/ex2.xlsx")

In [47]:
import requests

In [48]:
url='https://api.github.com/repos/pandas-dev/pandas/issues'

In [49]:
resp=requests.get(url)

In [50]:
resp

In [51]:
data=resp.json()

In [54]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27138',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27138/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27138/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27138/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/27138',
  'id': 462372225,
  'node_id': 'MDU6SXNzdWU0NjIzNzIyMjU=',
  'number': 27138,
  'title': 'Add MultiIndex._data and MultiIndex.array',
  'user': {'login': 'topper-123',
   'id': 26364415,
   'node_id': 'MDQ6VXNlcjI2MzY0NDE1',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/26364415?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/topper-123',
   'html_url': 'https://github.com/topper-123',
   'followers_url': 'https://api.github.com/users/topper-123/followers',
   'following_url': 'https://api.github.com/users/topper-123/following{/other_user}',
   'gists_url': 'https://api.github.com/users/topper-123/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/topper-123/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/topper-123/subscriptions',
   'organizations_url': 'https://api.github.com/users/topper-123/orgs',
   'repos_url': 'https://api.github.com/users/topper-123/repos',
   'events_url': 'https://api.github.com/users/topper-123/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/topper-123/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 35818298,
    'node_id': 'MDU6TGFiZWwzNTgxODI5OA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20Design',
    'name': 'API Design',
    'color': 'AD7FA8',
    'default': False},
   {'id': 71268330,
    'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex',
    'name': 'MultiIndex',
    'color': '207de5',
    'default': False}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2019-06-30T06:22:59Z',
  'updated_at': '2019-06-30T06:23:24Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'body': 'I propose adding a ``MultiIndex._data`` that is of type ``List[Categorical]``, where all the underlying data of a MultiIndex would be stored. A ``multiIndex.array`` property would also be added, that accesses the ``_data``.\r\n\r\nThis has the advantage of collecting the data that is underlying MultiIndex into one data structure, that is human readable, and also makes access to zero-copy data very easy, e.g. would ``mi.array[1]`` return the data of the second level as a ``Categorical``, in a easy-to-read form. \r\n\r\nA ``MultiIndex`` could with the above changes be explained as just "a container over a list of Categoricals", which is easier to explain than the current mode. The ``MultiIndex`` could also be related to ``CategoricalIndex``, which is "a container over a single Categorical".\r\n\r\nThis change means that ``MultiIndex.levels`` will become a property that returns a ``FrozenList(cat.categories for cat in self._data)``, and  ``MultiIndex.codes`` will be a property that returns ``FrozenList(cat.codes for cat in self._data)``.\r\n\r\n``MultiIndex.array`` will be added and will simply be a property that returns a FrozenList of ``self._data``.\r\n\r\nPerformance will not be affected, as most operations would still go through ``MultiIndex.codes`` and ``MultiIndex.levels``.\r\n\r\n## Moving names from MultiIndex.levels to MultiIndex._names\r\n\r\nCurrently the levels\' names are stored at each level\'s ``name`` attribute. This is not very compatible with extracting the categories from ``_data``. (the ``.categories`` is actually part of the dtype, which ideally should be immutable, so we shouldn\'t set or change its name attribute).\r\n\r\nTo make my suggestion practically possible, the level names should be stored in ``MultiIndex._names`` instead, and ``MultiIndex.names`` will become a property that reads from/writes to ``MultiIndex._names``. I think this change simplifies the  MultiIndex a bit, as data and names are dealt with separately. This is a small backward breaking change though.\r\n\r\nSo, I suggest making two PRs:\r\n\r\n1. Separating  the names from the levels (to be included in 0.25)\r\n2. Add ``_data``, ``array`` and change ``levels`` and ``codes`` into properties.\r\n\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27137',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27137/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27137/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27137/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/27137',
  'id': 462368873,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjkzMDgwMDg4',
  'number': 27137,
  'title': 'API: ExtensionArray.argsort places the missing value at the end ',
  'user': {'login': 'makbigc',
   'id': 14367887,
   'node_id': 'MDQ6VXNlcjE0MzY3ODg3',
   'avatar_url': 'https://avatars3.githubusercontent.com/u/14367887?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/makbigc',
   'html_url': 'https://github.com/makbigc',
   'followers_url': 'https://api.github.com/users/makbigc/followers',
   'following_url': 'https://api.github.com/users/makbigc/following{/other_user}',
   'gists_url': 'https://api.github.com/users/makbigc/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/makbigc/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/makbigc/subscriptions',
   'organizations_url': 'https://api.github.com/users/makbigc/orgs',
   'repos_url': 'https://api.github.com/users/makbigc/repos',
   'events_url': 'https://api.github.com/users/makbigc/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/makbigc/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2019-06-30T05:21:11Z',
  'updated_at': '2019-06-30T05:29:55Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/27137',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/27137',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/27137.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/27137.patch'},
  'body': 'continue #26354 \r\n\r\n1. Categorical will be handled in a separate PR.\r\n2. benchmark result:\r\n```\r\n       before           after         ratio\r\n     [989f912e]       [dc0ef701]\r\n     <master>         <enh-21801-2>\r\n+     11.4±0.03μs       36.8±0.1μs     3.23  algorithms.EASorting.time_argsort(1000)\r\n+       785±0.5μs      1.26±0.03ms     1.60  algorithms.EASorting.time_argsort(100000)\r\n\r\n```\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27136',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27136/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27136/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27136/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/27136',
  'id': 462353047,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjkzMDY5OTM1',
  'number': 27136,
  'title': 'PERF, BENCH: Fix performance issue when indexing into non-unique DatetimeIndex/PeriodIndex.',
  'user': {'login': 'qwhelan',
   'id': 440095,
   'node_id': 'MDQ6VXNlcjQ0MDA5NQ==',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/440095?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/qwhelan',
   'html_url': 'https://github.com/qwhelan',
   'followers_url': 'https://api.github.com/users/qwhelan/followers',
   'following_url': 'https://api.github.com/users/qwhelan/following{/other_user}',
   'gists_url': 'https://api.github.com/users/qwhelan/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/qwhelan/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/qwhelan/subscriptions',
   'organizations_url': 'https://api.github.com/users/qwhelan/orgs',
   'repos_url': 'https://api.github.com/users/qwhelan/repos',
   'events_url': 'https://api.github.com/users/qwhelan/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/qwhelan/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2019-06-30T00:13:47Z',
  'updated_at': '2019-06-30T00:51:07Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/27136',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/27136',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/27136.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/27136.patch'},
  'body': 'This PR fixes a number of issues involving non-unique non-numeric indexing:\r\n- The `NonNumericSeriesIndexing` benchmark incorrectly assumes `tm.makeStringIndex()` returns a monotonic `Index`. It does not and unfortunately invalidates the existing results here.\r\n  - While modifying this, figured should add `PeriodIndex` and `non_monotonic` cases\r\n- The `setup()` function creates an index but does not trigger the engine mapping to be populated. This leads to noisy and erroneous results.\r\n  - See here for examples and compare with below: https://pandas.pydata.org/speed/pandas/#indexing.NonNumericSeriesIndexing.time_getitem_scalar\r\n- A `PeriodIndex` or `DatetimeIndex` with non-unique, monotonic data creates an entirely new `Index` when being sliced. This means the engine mapping gets recomputed on every list-like query.\r\n- A `PeriodIndex` is actually a `PeriodEngine` plus a separate `Int64Index` (with associated `Int64Engine`). The former contains a mapping of `{Period: value}` while being a subclass of `Int64Engine`. This means calls to `_bin_search()` fail as the underlying array consists of `Period` objects. This only occurs when the index is non-unique, monotonic, *and* `>= 1M` elements long.\r\n  - We add an explicit test for this failure mode\r\n- A number of index calls pass `value.ordinal` to the `PeriodEngine`; as that is a `{Period: value}` mapping, all such calls fail.\r\n  - We instead pass `value.ordinal` queries to the `Int64Engine`, where they succeed.\r\n- Finally, `PeriodIndex.get_memory()` does not account for the memory of its associated `Int64Index`. This is fixed by simply adding it to the total.\r\n\r\n```\r\n       before           after         ratio\r\n     [2811464a]       [a68caa2a]\r\n     <import_bench~1>       <period_fix>\r\n           failed         62.4±2μs      n/a  indexing.NonNumericSeriesIndexing.time_get_value(\'period\', \'unique_monotonic_inc\')\r\n           failed         216±20μs      n/a  indexing.NonNumericSeriesIndexing.time_getitem_label_slice(\'period\', \'unique_monotonic_inc\')\r\n           failed      2.74±0.05ms      n/a  indexing.NonNumericSeriesIndexing.time_getitem_list_like(\'period\', \'unique_monotonic_inc\')\r\n           failed        160±0.5μs      n/a  indexing.NonNumericSeriesIndexing.time_getitem_pos_slice(\'period\', \'unique_monotonic_inc\')\r\n           failed       43.0±0.2μs      n/a  indexing.NonNumericSeriesIndexing.time_getitem_scalar(\'period\', \'unique_monotonic_inc\')\r\n-        718±10μs         207±10μs     0.29  indexing.NonNumericSeriesIndexing.time_getitem_label_slice(\'period\', \'non_monotonic\')\r\n-     2.53±0.05ms         701±10μs     0.28  indexing.NonNumericSeriesIndexing.time_getitem_list_like(\'period\', \'non_monotonic\')\r\n-      33.8±0.9ms      2.32±0.04ms     0.07  indexing.NonNumericSeriesIndexing.time_getitem_list_like(\'period\', \'nonunique_monotonic_inc\')\r\n-      62.7±0.5ms          532±3μs     0.01  indexing.NonNumericSeriesIndexing.time_getitem_list_like(\'datetime\', \'nonunique_monotonic_inc\')\r\n\r\n       before           after         ratio\r\n     [2811464a]       [a68caa2a]\r\n     <import_bench~1>       <period_fix>\r\n+      40.7±0.7μs       46.8±0.8μs     1.15  indexing.NonNumericSeriesIndexing.time_get_value(\'period\', \'non_monotonic\')\r\n+        27.0±2μs       30.4±0.6μs     1.12  indexing.NonNumericSeriesIndexing.time_getitem_scalar(\'period\', \'non_monotonic\')\r\n```\r\n\r\n- [ ] closes #xxxx\r\n- [ ] tests added / passed\r\n- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27135',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27135/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27135/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27135/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/27135',
  'id': 462341487,
  'node_id': 'MDU6SXNzdWU0NjIzNDE0ODc=',
  'number': 27135,
  'title': 'read_json different behaviour when file is os path or file url',
  'user': {'login': 'gtmaskall',
   'id': 9091454,
   'node_id': 'MDQ6VXNlcjkwOTE0NTQ=',
   'avatar_url': 'https://avatars3.githubusercontent.com/u/9091454?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/gtmaskall',
   'html_url': 'https://github.com/gtmaskall',
   'followers_url': 'https://api.github.com/users/gtmaskall/followers',
   'following_url': 'https://api.github.com/users/gtmaskall/following{/other_user}',
   'gists_url': 'https://api.github.com/users/gtmaskall/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/gtmaskall/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/gtmaskall/subscriptions',
   'organizations_url': 'https://api.github.com/users/gtmaskall/orgs',
   'repos_url': 'https://api.github.com/users/gtmaskall/repos',
   'events_url': 'https://api.github.com/users/gtmaskall/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/gtmaskall/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2019-06-29T20:55:19Z',
  'updated_at': '2019-06-29T20:55:19Z',
  'closed_at': None,
  'author_association': 'NONE',
  'body': '#### Code Sample, a copy-pastable example if possible\r\n```bash\r\npwd\r\n/home/guy/tmp\r\necho -e \'{"a": 1, "b": 2}\\n{"a": 3, "b": 4}\' > test.json\r\ncat test.json \r\n{"a": 1, "b": 2}\r\n{"a": 3, "b": 4}\r\n```\r\n\r\n```python\r\n# Your code here\r\n[ins] In [74]: ospath = \'/home/guy/tmp/test.json\'                                                                       \r\n\r\n[ins] In [75]: fileurl = \'file://localhost/home/guy/tmp/test.json\'                                                      \r\n\r\n[nav] In [76]: import pandas as pd                                                                                      \r\n\r\n[ins] In [77]: pd.read_json(ospath, lines=True)                                                                         \r\nOut[77]: \r\n   a  b\r\n0  1  2\r\n1  3  4\r\n\r\n[ins] In [78]: pd.read_json(fileurl, lines=True)                                                                        \r\nOut[78]: \r\n   a  b\r\n0  1  2\r\n1  3  4\r\n\r\n[ins] In [79]: reader = pd.read_json(ospath, lines=True, chunksize=1)                                                   \r\n\r\n[ins] In [80]: for chunk in reader: \r\n          ...:     print(chunk) \r\n          ...:                                                                                                          \r\n   a  b\r\n0  1  2\r\n   a  b\r\n1  3  4\r\n\r\n[ins] In [81]: reader = pd.read_json(fileurl, lines=True, chunksize=1)\r\n```\r\n#### Problem description\r\nCreate a very simple two-line JSON file. Specify the location of the file two ways - using an OS path, and using a file URL. Both allow read_json() to read the JSON when read in one go. If using chunksize to create a reader, only the OS path specifier works. Trying to use the file path specifier produces a TypeError: sequence item 0: expected str instance, bytes found\r\n\r\nThe read_json doc says:\r\npath_or_buf : a valid JSON string or file-like, default: None\r\n    The string could be a URL. Valid URL schemes include http, ftp, s3,\r\n    gcs, and file. For file URLs, a host is expected. For instance, a local\r\n    file could be ``file://localhost/path/to/table.json``\r\n\r\nThis leads to the expectation that a file URL should behave the same as a simple OS path under all use cases.\r\n\r\nI think this is the root cause of the problem described under issue   #27022\r\n```\r\n# output when using fileurl:\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-82-605ab8a466fd> in <module>\r\n----> 1 for chunk in reader:\r\n      2     print(chunk)\r\n      3 \r\n\r\n~/anaconda3/envs/test_latest_pandas_json/lib/python3.7/site-packages/pandas/io/json/json.py in __next__(self)\r\n    579         lines = list(islice(self.data, self.chunksize))\r\n    580         if lines:\r\n--> 581             lines_json = self._combine_lines(lines)\r\n    582             obj = self._get_object_parser(lines_json)\r\n    583 \r\n\r\n~/anaconda3/envs/test_latest_pandas_json/lib/python3.7/site-packages/pandas/io/json/json.py in _combine_lines(self, lines)\r\n    520         """\r\n    521         lines = filter(None, map(lambda x: x.strip(), lines))\r\n--> 522         return \'[\' + \',\'.join(lines) + \']\'\r\n    523 \r\n    524     def read(self):\r\n\r\nTypeError: sequence item 0: expected str instance, bytes found\r\n```\r\n\r\n[ins] In [83]: pd.__version__                                                                                           \r\nOut[83]: \'0.24.2\'\r\n\r\n\r\n#### Expected Output\r\nBehaviour of read_json to be the same regardless of the type of file-like.\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\n[paste the output of ``pd.show_versions()`` here below this line]\r\n                                                                            \r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit: None\r\npython: 3.7.3.final.0\r\npython-bits: 64\r\nOS: Linux\r\nOS-release: 5.0.0-20-generic\r\nmachine: x86_64\r\nprocessor: x86_64\r\nbyteorder: little\r\nLC_ALL: None\r\nLANG: en_GB.UTF-8\r\nLOCALE: en_GB.UTF-8\r\n\r\npandas: 0.24.2\r\npytest: None\r\npip: 19.1.1\r\nsetuptools: 41.0.1\r\nCython: None\r\nnumpy: 1.16.4\r\nscipy: None\r\npyarrow: None\r\nxarray: None\r\nIPython: 7.5.0\r\nsphinx: None\r\npatsy: None\r\ndateutil: 2.8.0\r\npytz: 2019.1\r\nblosc: None\r\nbottleneck: None\r\ntables: None\r\nnumexpr: None\r\nfeather: None\r\nmatplotlib: 3.1.0\r\nopenpyxl: None\r\nxlrd: None\r\nxlwt: None\r\nxlsxwriter: None\r\nlxml.etree: None\r\nbs4: None\r\nhtml5lib: None\r\nsqlalchemy: None\r\npymysql: None\r\npsycopg2: None\r\njinja2: 2.10.1\r\ns3fs: None\r\nfastparquet: None\r\npandas_gbq: None\r\npandas_datareader: None\r\ngcsfs: None\r\n</details>\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/27134',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',

In [55]:
issues =pd.DataFrame(data,columns=['number','title','labels','state'])
issues

,number,title,labels,state
0,27138,Add MultiIndex._data and MultiIndex.array,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
1,27137,API: ExtensionArray.argsort places the missing...,[],open
2,27136,"PERF, BENCH: Fix performance issue when indexi...",[],open
3,27135,read_json different behaviour when file is os ...,[],open
4,27134,BUG: Timedelta repr doesn't show nano,[],open
5,27133,Add Index.__array_ufunc__,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
6,27132,DOC: tweak paragraph regarding cut and Interva...,[],open
7,27131,"DOC: add internal links to ""Endpoints are incl...",[],open
8,27130,BUG: Fix Series divmod #26987,[],open
9,27127,BUG: GH26944,[],open
10,27125,BUG: Index constructor should not allow an nda...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
11,27124,TST: flaky test test_agg_consistency on Python...,"[{'id': 76939933, 'node_id': 'MDU6TGFiZWw3Njkz...",open
12,27123,Allow 2D arrays in DataFrame.from_dict,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
13,27122,Regenerated Excel files to Suppress Openpyxl W...,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
14,27119,PERF: do not instantiate IndexEngine for stand...,[],open
15,27118,Plotting ExtensionArrays,[],open
16,27117,Make pandas.to_parquet handles partition colum...,"[{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...",open
17,27116,Bump python_requires to 3.5.3,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
18,27110,BUG: Fix indexing on DatetimeBlock,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
19,27109,DEPR: remove deprecated date casting; closes #...,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
20,27108,API: Add property to Index to disallow duplicates,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
21,27104,Partial indexing with list on MultiIndex with ...,"[{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...",open
22,27101,CLN/DEPR: Final panel removal,"[{'id': 452722332, 'node_id': 'MDU6TGFiZWw0NTI...",open
23,27100,API: Implement new indexing behavior for inter...,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
24,27099,Join operation takes more time.,[],open
25,27098,DEPR: DatetimeIndex.snap(),"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
26,27096,Clean Up Testing of Excel Engine Option Settin...,"[{'id': 49254273, 'node_id': 'MDU6TGFiZWw0OTI1...",open
27,27095,Shorter truncated Series/DataFrame repr: intro...,"[{'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEw...",open
28,27093,Change in column name creates an empty output ...,[],open
29,27092,Update visualization.rst,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open